name: Release to Beta Channel
# https://plugins.jetbrains.com/plugin/5925-codenarc/versions/beta

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: "-Xmx6g -Xms4g -Dorg.gradle.daemon=false"
      CI: true
    steps:
      - name: Set dynamic Beta version
        id: version_step
        run: |
          # Expected result example: BETA_VERSION=7.0.1-20220126120000
          PLUGIN_VERSION=$(grep 'pluginVersion' gradle.properties | awk -F'=' '{print $2}' | tr -d '[:space:]')
          BETA_SUFFIX=$(date +%Y%m%d%H%M%S)
          echo "BETA_VERSION=${PLUGIN_VERSION}-${BETA_SUFFIX}" >> $GITHUB_ENV
      - name: Checkout source
        uses: actions/checkout@v6
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Build and publish to JetBrains Marketplace Beta channel with Gradle
        run: |
          ./gradlew publishPlugin \ 
            -PpublishPluginChannels=beta \ 
            -PpluginVersion=${{ env.BETA_VERSION }} \
            -PpublishPluginToken=${{ secrets.JB_PLUGINS_TOKEN }}
